### PR TITLE
Java solution for issue #391  LeetCode problem - 136 (Single Number)

### PR DESCRIPTION
**Pull request by siddharthamishra1207**
Please review the code and if no changes are required please merge the pull request.

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Atleast wait for sometime, this issue was not assigned to you.
Next time I will not be merging your PR if you repeat the same.

**Comment by tanyagupta0201** [comment]
give space between // and first word

**Comment by siddharthamishra1207** [comment]
please merge my pull request

**Comment by tanyagupta0201** [comment]
#391

**Pull request merged**
