### PR TITLE
Create 21_Merge_Two_Sorted_Lists.java

### PR DESCRIPTION
**Pull request by Aaditya1612**
@tanyagupta0201 Please merge my PR under HacktoberFest.
Issue #281.

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
adding comments in your code will be helpful

**Comment by Aaditya1612** [comment]
@tanyagupta0201 Added comments to explain the code. Please check now.

**Comment by tanyagupta0201** [comment]
filename not according to guidelines. 
give space between // and first word, in some comments you have not given it.

**Comment by Aaditya1612** [comment]
@tanyagupta0201 Done all the required changes.

**Pull request merged**
