### PR TITLE
added solution to issue #318

### PR DESCRIPTION
**Pull request by milostivyy**
I have added the solution pls check it and if correct give hacktoberfest-accepted .Thanks:)

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Kindly give a space between // and first word.

**Comment by milostivyy** [comment]
I have corrected the code. Kindly review it and give it hacktoberfest-accepted label to issue #318 and to issue #235 .

**Comment by tanyagupta0201** [comment]
You have corrected shortest bridge
but did not space in island perimeter code

**Comment by milostivyy** [comment]
I have done corrections for island perimeter code , which is issue  #235 .Pls check and review it and kindly  give hacktoberfest-accepted label to both shortest bridge code issue no #318 and island perimeter code issue no #235 .
Thank you :)

**Comment by milostivyy** [comment]
I have added solution to issue #356 .Pls review it and kindly give it hacktoberfest-accepted.Thanks:)

**Pull request merged**
