### PR TITLE
Added Solution for problem 752 of Leetcode

### PR DESCRIPTION
**Pull request by kshibarn**
Added Solution for problem 752 of Leetcode

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
1. unformatted code
2. add comments to explain code

**Comment by tanyagupta0201** [comment]
What is the issue number of this problem ? Mention that here.

**Comment by kshibarn** [comment]
Updated my code with comments and formatted my code.
My issue number is 576

**Comment by tanyagupta0201** [comment]
> Updated my code with comments and formatted my code. My issue number is 576

well that's not 576. Anyways, I am merging this code.

**Pull request merged**
