### PR TITLE
Added problem 39 of leetcode

### PR DESCRIPTION
**Pull request by shreya-jpg**
**Please add this for Hacktoberfest 2022.**

Problem description: Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target. You may return the combinations in any order.

The same number may be chosen from candidates an unlimited number of times. Two combinations are unique if the frequency of at least one of the chosen numbers is different.

The test cases are generated such that the number of unique combinations that sum up to target is less than 150 combinations for the given input.

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
code not according to guidelines. Do read them.

**Comment by shreya-jpg** [comment]
#435 Added

**Comment by tanyagupta0201** [comment]
Slightly unformatted. You may use link in the guidelines to format your code.

**Comment by shreya-jpg** [comment]
> Slightly unformatted. You may use link in the guidelines to format your code.

updates

**Pull request merged**
