### PR TITLE
Leetcode  no.72 solution and explaination

### PR DESCRIPTION
**Pull request by jaisinha**
The given changes were implemented

1)Name and the editing date
2)Documentation
3)Executable code
4)Formatting is done by given c++ formatted

Pl take a look @tanyagupta0201

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
sir, your code is well explained but it is not following the leetcode pattern.

**Comment by tanyagupta0201** [comment]
take an idea from other merged solutions

**Comment by jaisinha** [comment]
Yes I saw,some of them created only the required function in class while other did the whole code.

I took reference from 5_LongestPalindromicSubstring.cpp in your c++ rep

**Comment by tanyagupta0201** [comment]
> Yes I saw,some of them created only the required function in class while other did the whole code.
> 
> I took reference from 5_LongestPalindromicSubstring.cpp in your c++ rep

Sorry my bad. I would replace that file ASAP.

**Comment by tanyagupta0201** [comment]
Please follow the leetcode boilerplate

**Comment by tanyagupta0201** [comment]
stale PR

**Pull request closed without merging**
