### PR TITLE
#342 issue

### PR DESCRIPTION
**Pull request by chharikha2003**

### CODE REVIEW

**Comment by chharikha2003** [comment]
Added python code to check if a number is a Pangram

**Comment by tanyagupta0201** [comment]
Give a space between # and first word

**Comment by chharikha2003** [comment]
There is space

**Comment by chharikha2003** [comment]
There is space.Can you please check once again

**Comment by tanyagupta0201** [comment]
> There is space.Can you please check once again

It shows me 2 codes. This code is okay. You need to add space in "Swap nodes in pairs" code.

**Comment by chharikha2003** [comment]
There is space.Can you please check once again

**Comment by chharikha2003** [comment]
Ok can you please merge this

**Comment by tanyagupta0201** [comment]
> Ok can you please merge this

Since 2 files are shown together if I will try to merge this PR then both of them give get merged at the same time.

**Comment by tanyagupta0201** [comment]
image


you have also not given space between = and variables. Need to give there also

**Comment by chharikha2003** [comment]
I will make the changes now

**Comment by tanyagupta0201** [comment]
> I will make the changes now

between = and variables too

**Pull request closed without merging**
