### PR TITLE
remove k digits

### LINKED ISSUE #117: 402. Remove k digits
description: Given string num representing a non-negative integer num, and an integer k, return the smallest possible integer after removing k digits from num.
#JAVA
@tanyagupta0201,  Please assign this task to me with Hacktoberfest2022 label

### PR DESCRIPTION
**Pull request by MadhuSaini22**
resolves #117

### CODE REVIEW

**Comment by MadhuSaini22** [comment]
@tanyagupta0201 , Please add Hacktoberfest2022 accepted label on merged PRs.

**Comment by tanyagupta0201** [comment]
Code is not formatted properly

**Comment by tanyagupta0201** [comment]
Why are you adding java file into Python folder ?

**Comment by MadhuSaini22** [comment]
ohh sorry my bad, I'll correct that out

**Pull request closed without merging**
