### PR TITLE
Problem 206 reverse linkedlist in java.

### PR DESCRIPTION
**Pull request by Kr-Shanu**
Simple and short code with full explanation.

### CODE REVIEW

**Review by nungster — APPROVED** [review]
LGTM

**Comment by Kr-Shanu** [comment]
Renamed the file names according to the guidelines.

**Comment by tanyagupta0201** [comment]
Comments in the following lines are not properly written 
Line 24 to 27.
Line 6

**Comment by Kr-Shanu** [comment]
I really apologise as I did not make an issue before this pull request, but I recently added the issue with issue #195

**Comment by tanyagupta0201** [comment]
Merging this now but do follow the point 2 of the guidelines from the next time

**Pull request merged**
