### PR TITLE
42_TrappingRainWater.cpp

### PR DESCRIPTION
**Pull request by shivesh41kr**

### CODE REVIEW

**Comment by shivesh41kr** [comment]
@tanyagupta0201 please merge this PR.

**Comment by tanyagupta0201** [comment]
Name and date not added.
Kindly use the link given in guidelines to format your code.

**Comment by tanyagupta0201** [comment]
File name also not according to guidelines

**Comment by shivesh41kr** [comment]
> File name also not according to guidelines

solved, please have a look on this.

**Comment by tanyagupta0201** [comment]
Name and date must be on top
then write intution

**Pull request closed without merging**
