### PR TITLE
50. Pow

### PR DESCRIPTION
**Pull request by Bcepnez**
solution for 50 Pow(x, n) in PYTHON version

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
File name is not according to guidelines.

**Comment by tanyagupta0201** [comment]
correct it

**Comment by Bcepnez** [comment]
ok sorry wait a min

**Comment by tanyagupta0201** [comment]
Still incorrect

**Comment by tanyagupta0201** [comment]
Dude, the file name should be ``50_Pow(x, n).py``

**Comment by Bcepnez** [comment]
renamed

**Pull request closed without merging**
