### PR TITLE
16_3Sum_Closest.cpp

### PR DESCRIPTION
**Pull request by Niveshpai**

### CODE REVIEW

**Review by Niveshpai — COMMENTED** [review]
Changed as per guidelines

**Comment by tanyagupta0201** [comment]
File name is not according to guidelines

**Comment by tanyagupta0201** [comment]
Also add valuable comments to explain your code

**Review by Niveshpai — COMMENTED** [review]
resolves #135
Added proper comments for the code.

**Review by Niveshpai — COMMENTED** [review]
Changed suitable title name

**Comment by tanyagupta0201** [comment]
In some lines, space is not given between // and first word

**Comment by Niveshpai** [comment]
Changed the same.

**Pull request merged**
