### PR TITLE
Create 21_MergeTwoSortedList.java

### PR DESCRIPTION
**Pull request by MadhuSaini22**
resolves issue #148

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Adding comments to your codes will give a better understanding of the code.

**Comment by MadhuSaini22** [comment]
@tanyagupta0201 , I've updated my code. Please verify :)

**Comment by MadhuSaini22** [comment]
@tanyagupta0201 , Please verify the code and let me know if require any changes.

**Comment by MadhuSaini22** [comment]
@tanyagupta0201 , Please verify the code and let me know if require any changes.

**Pull request merged**
