### PR TITLE
12. Integer to Roman

### PR DESCRIPTION
**Pull request by adarshgupta404**
Please review and merge

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Your code is not formatted properly. Use the link given in the guidelines.

**Comment by adarshgupta404** [comment]
> Your code is not formatted properly. Use the link given in the guidelines.

can you mention which guideline?

**Comment by tanyagupta0201** [comment]
> > Your code is not formatted properly. Use the link given in the guidelines.
> 
> can you mention which guideline?

In the guidelines, I have provided the links to format the code. Use them.

**Comment by adarshgupta404** [comment]
Ma'am please review.

**Pull request merged**
