### PR TITLE
1_Add_Two_Numbers

### PR DESCRIPTION
**Pull request by BishtAmi**
kindly verify and merge @tanyagupta0201

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Against the guidelines

**Comment by BishtAmi** [comment]
what happened?

**Comment by tanyagupta0201** [comment]
> 
Is the filename according to the guidelines? Did you add comments to explain your code? Is your name and date written properly as shown in the image in guidelines?

**Comment by BishtAmi** [comment]
can I edit and pull it again @tanyagupta0201

**Pull request closed without merging**
