### PR TITLE
19th Remove Nth Node From End of List.cpp

### PR DESCRIPTION
**Pull request by shivesh41kr**
Leetcode Problem No. - 19.  - Remove Nth Node From End of List Solution With comments and Optimized.

### CODE REVIEW

**Comment by shivesh41kr** [comment]
Leetcode Problem No. - 19. - Remove Nth Node From End of List Solution With comments and Optimized.

**Comment by shivesh41kr** [comment]
@tanyagupta0201 Please merge my PR #254 under Hacktoberfest

**Comment by tanyagupta0201** [comment]
Add your name and date
give space between // and first word

**Comment by tanyagupta0201** [comment]
stale

**Pull request closed without merging**
