### PR TITLE
Bitwise XOR of All Pairings solution added

### PR DESCRIPTION
**Pull request by niteshkumar257**
Added the solution with an explanation 
Please review  it

### CODE REVIEW

**Review by nungster — APPROVED** [review]
LGTM

**Comment by tanyagupta0201** [comment]
Your code is not formatted properly. Use the link given in the guidelines to format your code.
Also add date and name according to the guidelines.

**Comment by tanyagupta0201** [comment]
And do not add main function. Keep the boilerplate according to the leetcode boilerplate.

**Comment by niteshkumar257** [comment]
ok

**Comment by niteshkumar257** [comment]
Can you please review this 
I changed the code as you said

**Comment by tanyagupta0201** [comment]
Code is not formatted properly now also

**Pull request closed without merging**
