### PR TITLE
Please add my C++ Solution to prob no 1578

### PR DESCRIPTION
**Pull request by Naman027**
Solution added for 1578_MinimumTimeToMakeRopeColorful

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Your code is not formatted according to the guidelines. Use the link given in the guidelines to format your code.

**Comment by Naman027** [comment]
I have formatted the code now.

**Comment by tanyagupta0201** [comment]
Add comments to explain your code. This will be helpful!

**Comment by tanyagupta0201** [comment]
Make sure to give space between // and first word

**Comment by Naman027** [comment]
Added Comments to C++ Solution of prob 1578

**Comment by Naman027** [comment]
Added Comments to C++ Solution of prob 85

**Pull request merged**
