### PR TITLE
Added solution to Leetcode problem no. 2425 and 1192.

### PR DESCRIPTION
**Pull request by rishabh-arya**

### CODE REVIEW

**Review by swarajpande4 — COMMENTED** [review]
Add the required comments at the beginning of the file.

**Comment by rishabh-arya** [comment]
Sorry !
I will make the required changes and also raising the issue for these problems as well.

**Comment by rishabh-arya** [comment]
@tanyagupta0201 Issue #198

**Comment by tanyagupta0201** [comment]
> @tanyagupta0201 Issue #198

Merging your PR now. Make sure to raise an issue and make a PR only after you are assigned that issue for the next time otherwise I would not merge it.

**Comment by rishabh-arya** [comment]
@tanyagupta0201  Thanks for the favour !

**Pull request merged**
