### PR TITLE
Added problem 39 of leetcode in java.

### PR DESCRIPTION
**Pull request by Kr-Shanu**
Used recursion method to find the solution, with full explanation.

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
File name is not according to guidelines

**Comment by Kr-Shanu** [comment]
Have changed the file name according to the guidelines.
@tanyagupta0201 please have a look at it.

**Comment by tanyagupta0201** [comment]
Kindly mention issue number of this problem in the comments. So, that it can be closed after merging this code.

**Comment by Kr-Shanu** [comment]
Really sorry @tanyagupta0201 i didn't make an issue for two of the pull request, would make it right now and mention it below.

**Comment by Kr-Shanu** [comment]
Requested the given PR in the issue #192

**Pull request merged**
