### PR TITLE
3. Longest Substring Without Repeating Characters

### PR DESCRIPTION
**Pull request by souvikpal2000**

### CODE REVIEW

**Comment by souvikpal2000** [comment]
Can you please merge this.

**Comment by tanyagupta0201** [comment]
Your code is slightly unformatted. Use the link given in the guidelines to format your code.

**Comment by souvikpal2000** [comment]
Code formatted using the link given in the guidelines.

**Comment by tanyagupta0201** [comment]
Kindly add some comments to explain your code. This will be helpful.

**Comment by souvikpal2000** [comment]
> Kindly add some comments to explain your code. This will be helpful.

In the comment, I've copy pasted full LEETCODE question. In the examples it is explained clearly.

**Comment by souvikpal2000** [comment]
And I've seen other merged PR, they only written their name & date but not explained the code.

**Comment by tanyagupta0201** [comment]
> @tanyagupta0201 ... I've seen other merged PR, they only written their name & date but not explained the code.

Yes, but now I'm not merging codes without explanation. I read the guidelines again again of the fest. They want quality codes otherwise they can exclude the repo from the fest. Adding comments would help the users to understand your solution efficiently

**Comment by tanyagupta0201** [comment]
You may see I am asking other people also to add comments.

**Comment by souvikpal2000** [comment]
Now please check, whether it is correct or not.

**Pull request merged**
