### PR TITLE
added solutions of some leetcode questions in cpp

### PR DESCRIPTION
**Pull request by ShubhamYadav7063**
leetcode cpp questions

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
Your code is not formatted properly. Use the link given in the guidelines to format your code.

**Comment by tanyagupta0201** [comment]
You may add comments to explain your codes

**Comment by ShubhamYadav7063** [comment]
okay sure

**Comment by tanyagupta0201** [comment]
stale PR

**Pull request closed without merging**
