### PR TITLE
 633_SumofSquareNumbers.cpp

### PR DESCRIPTION
**Pull request by roy2pushkar**

### CODE REVIEW

**Comment by roy2pushkar** [comment]
@tanyagupta0201 Please merge my project under Hacktoberfest ###

**Comment by tanyagupta0201** [comment]
code is not formatted properly.
add comments to explain your code.

**Comment by roy2pushkar** [comment]
@tanyagupta0201  now check

**Comment by tanyagupta0201** [comment]
> @tanyagupta0201 now check

Still it is slightly unformatted.
You may use the link given in the guidelines to format your code

**Comment by roy2pushkar** [comment]
@tanyagupta0201  please check #291 issues . now it is in formatted and  proper comments to explain to code.

**Comment by tanyagupta0201** [comment]
image


I don't see any comment. Also, give a space between // and first word when you add comments.

**Comment by roy2pushkar** [comment]
@tanyagupta0201  now i think everything done please check

**Comment by tanyagupta0201** [comment]
> @tanyagupta0201 now i think everything done please check

3 comments left to give space.
why are you leaving a line after each statement ? It is not looking nice. Take reference from other merged codes.

**Comment by roy2pushkar** [comment]
formatted @tanyagupta0201 #291

**Comment by tanyagupta0201** [comment]
#231

**Pull request merged**
