### PR TITLE
Create 977_SquaresofaSortedArray.cpp

### PR DESCRIPTION
**Pull request by surbhisawan**
@tanyagupta0201 Please merge my PR under Hacktoberfest.
Issue #411

### CODE REVIEW

**Comment by tanyagupta0201** [comment]
need to wait until the issue is assigned to you

**Comment by tanyagupta0201** [comment]
Next time it would not be merged directly.

**Comment by tanyagupta0201** [comment]
File name not according to guidelines. Leave space between // and first word.

**Comment by surbhisawan** [comment]
> need to wait until the issue is assigned to you

issue #411

**Comment by surbhisawan** [comment]
> File name not according to guidelines. Leave space between // and first word.

Done the respective changes.

**Comment by surbhisawan** [comment]
Kindly look into it.

**Pull request merged**
